name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git checkout -B gh-pages
          git rm -rf .

          cp -r site/* .

          git add .
          git commit -m "Deploy site"
          git push origin gh-pages --force
